on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write

name: Build and Release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org

      - name: Verify versions
        run: node --version && npm --version && node -p process.versions.v8

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Release package
        run: npm publish --ignore-scripts --provenance
